# Generated by Django 5.0.6 on 2025-07-06 11:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_bookingcar_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingcar',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
