# Generated by Django 5.0.6 on 2025-07-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_bookingcar_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
